// ─────────────────────────────────────────────
//  Mock Data — Personagens do Naruto
//  Usado quando a API está inacessível
// ─────────────────────────────────────────────

export const mockCharacters = [
  {
    id: 1,
    name: "Naruto Uzumaki",
    images: ["https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_Part_I.png"],
    jutsu: ["Kage Bunshin no Jutsu", "Rasengan", "Tajuu Kage Bunshin no Jutsu", "Rasenshuriken", "Kurama Chakra Mode"],
    natureType: ["Wind", "Earth", "Water", "Fire", "Lightning", "Yin", "Yang"],
    personal: {
      clan: "Uzumaki Clan",
      birthdate: "October 10",
      sex: "Male",
      age: { "Part I": "12–13", "Part II": "15–17" },
      height: { "Part I": "145.3 cm", "Part II": "166 cm" },
      weight: { "Part I": "40.1 kg", "Part II": "50.9 kg" },
      bloodType: "B",
      affiliation: ["Konohagakure", "Mount Myōboku", "Allied Shinobi Forces"],
      team: ["Team Kakashi", "Team 7"],
      rank: { "Part I": "Genin", "Part II": "Genin" },
    },
    debut: { manga: "Chapter #1", anime: "Naruto Episode #1" },
    family: { father: "Minato Namikaze", mother: "Kushina Uzumaki" },
    uniqueTraits: ["Jinchūriki of the Nine-Tails", "Sage Mode", "Six Paths Sage Mode"],
  },
  {
    id: 2,
    name: "Sasuke Uchiha",
    images: ["https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_I.png"],
    jutsu: ["Chidori", "Sharingan", "Amaterasu", "Susanoo", "Kirin"],
    natureType: ["Lightning", "Fire", "Wind", "Earth", "Water", "Yin"],
    personal: {
      clan: "Uchiha Clan",
      birthdate: "July 23",
      sex: "Male",
      age: { "Part I": "12–13", "Part II": "16–17" },
      height: { "Part I": "150.8 cm", "Part II": "168 cm" },
      bloodType: "AB",
      affiliation: ["Konohagakure", "Otogakure", "Akatsuki"],
      team: ["Team 7"],
    },
    debut: { manga: "Chapter #3", anime: "Naruto Episode #1" },
    family: { father: "Fugaku Uchiha", mother: "Mikoto Uchiha", brother: "Itachi Uchiha" },
    uniqueTraits: ["Sharingan", "Mangekyō Sharingan", "Rinnegan", "Eternal Mangekyō Sharingan"],
  },
  {
    id: 3,
    name: "Sakura Haruno",
    images: ["https://static.wikia.nocookie.net/naruto/images/a/a0/Sakura_Part_I.png"],
    jutsu: ["Chakra Enhanced Strength", "Byakugō no Jutsu", "Yin Seal Release", "Cherry Blossom Impact"],
    natureType: ["Earth", "Water", "Fire", "Yin", "Yang"],
    personal: {
      clan: "Haruno Clan",
      birthdate: "March 28",
      sex: "Female",
      age: { "Part I": "12–13", "Part II": "15–17" },
      bloodType: "O",
      affiliation: ["Konohagakure"],
      team: ["Team 7"],
    },
    debut: { manga: "Chapter #3", anime: "Naruto Episode #1" },
    family: { father: "Kizashi Haruno", mother: "Mebuki Haruno" },
    uniqueTraits: ["Byakugō Seal", "Exceptional chakra control", "Medical Ninjutsu master"],
  },
  {
    id: 4,
    name: "Kakashi Hatake",
    images: ["https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png"],
    jutsu: ["Chidori", "Kamui", "Raikiri", "Shadow Clone Technique", "Lightning Beast Running Technique"],
    natureType: ["Lightning", "Earth", "Water", "Fire", "Wind"],
    personal: {
      clan: "Hatake Clan",
      birthdate: "September 15",
      sex: "Male",
      age: { "Part I": "26–27", "Part II": "29–31" },
      bloodType: "O",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      team: ["Team Minato", "Team 7"],
      rank: "Jonin",
    },
    debut: { manga: "Chapter #3", anime: "Naruto Episode #1" },
    family: { father: "Sakumo Hatake" },
    uniqueTraits: ["Copy Ninja", "Sharingan (transplanted)", "Mangekyō Sharingan"],
  },
  {
    id: 5,
    name: "Rock Lee",
    images: ["https://static.wikia.nocookie.net/naruto/images/7/7f/Rock_Lee_Part_II.png"],
    jutsu: ["Primary Lotus", "Hidden Lotus", "Eight Gates", "Leaf Whirlwind", "Drunken Fist"],
    natureType: [],
    personal: {
      birthdate: "November 27",
      sex: "Male",
      age: { "Part I": "13", "Part II": "17" },
      bloodType: "A",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      team: ["Team Guy"],
      rank: "Genin",
    },
    debut: { manga: "Chapter #36", anime: "Naruto Episode #21" },
    uniqueTraits: ["Cannot use ninjutsu or genjutsu", "Eight Gates master", "Taijutsu specialist"],
  },
  {
    id: 6,
    name: "Gaara",
    images: ["https://static.wikia.nocookie.net/naruto/images/2/2e/Gaara_Part_I.png"],
    jutsu: ["Sand Binding Coffin", "Sand Waterfall Funeral", "Shield of Sand", "Desert Suspension", "Sand Clone"],
    natureType: ["Earth", "Wind", "Lightning"],
    personal: {
      clan: "Kazekage Clan",
      birthdate: "January 19",
      sex: "Male",
      age: { "Part I": "12–13", "Part II": "15–17" },
      bloodType: "AB",
      affiliation: ["Sunagakure", "Allied Shinobi Forces"],
      rank: "Kazekage",
    },
    debut: { manga: "Chapter #35", anime: "Naruto Episode #20" },
    family: { father: "Rasa", sister: "Temari", brother: "Kankurō" },
    uniqueTraits: ["Former Jinchūriki of Shukaku", "Absolute sand defense", "No sleep needed"],
  },
  {
    id: 7,
    name: "Hinata Hyūga",
    images: ["https://static.wikia.nocookie.net/naruto/images/b/b9/Hinata_Part_I.png"],
    jutsu: ["Byakugan", "Gentle Fist", "Twin Lion Fist", "Eight Trigrams Sixty-Four Palms"],
    natureType: ["Fire", "Lightning"],
    personal: {
      clan: "Hyūga Clan",
      birthdate: "December 27",
      sex: "Female",
      age: { "Part I": "12", "Part II": "16" },
      bloodType: "A",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      team: ["Team Kurenai"],
    },
    debut: { manga: "Chapter #34", anime: "Naruto Episode #1" },
    family: { father: "Hiashi Hyūga", sister: "Hanabi Hyūga" },
    uniqueTraits: ["Byakugan", "Gentle Fist style", "360° vision"],
  },
  {
    id: 8,
    name: "Neji Hyūga",
    images: ["https://static.wikia.nocookie.net/naruto/images/9/95/Neji_Part_I.png"],
    jutsu: ["Byakugan", "Eight Trigrams Sixty-Four Palms", "Eight Trigrams Palm Rotation", "Gentle Fist"],
    natureType: ["Fire", "Earth"],
    personal: {
      clan: "Hyūga Clan",
      birthdate: "July 3",
      sex: "Male",
      age: { "Part I": "13", "Part II": "17" },
      bloodType: "O",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      team: ["Team Guy"],
      rank: "Jonin",
    },
    debut: { manga: "Chapter #36", anime: "Naruto Episode #21" },
    family: { father: "Hizashi Hyūga", uncle: "Hiashi Hyūga", cousin: "Hinata Hyūga" },
    uniqueTraits: ["Byakugan", "Prodigy of the Hyūga Clan", "360° field of vision"],
  },
  {
    id: 9,
    name: "Shikamaru Nara",
    images: ["https://static.wikia.nocookie.net/naruto/images/1/10/Shikamaru_Part_I.png"],
    jutsu: ["Shadow Imitation Technique", "Shadow Sewing Technique", "Shadow Neck Bind Technique"],
    natureType: ["Earth", "Fire", "Yin"],
    personal: {
      clan: "Nara Clan",
      birthdate: "September 22",
      sex: "Male",
      age: { "Part I": "12–13", "Part II": "16–17" },
      bloodType: "AB",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      team: ["Team Asuma"],
      rank: "Chunin",
    },
    debut: { manga: "Chapter #34", anime: "Naruto Episode #1" },
    family: { father: "Shikaku Nara", mother: "Yoshino Nara" },
    uniqueTraits: ["IQ over 200", "Laziest ninja", "Brilliant strategist"],
  },
  {
    id: 10,
    name: "Itachi Uchiha",
    images: ["https://static.wikia.nocookie.net/naruto/images/b/bb/Itachi_Uchiha.png"],
    jutsu: ["Amaterasu", "Tsukuyomi", "Susanoo", "Izanami", "Crow Clone Technique"],
    natureType: ["Fire", "Water", "Wind", "Yin"],
    personal: {
      clan: "Uchiha Clan",
      birthdate: "June 9",
      sex: "Male",
      age: { "Part I": "17–18", "Part II": "21" },
      bloodType: "AB",
      affiliation: ["Konohagakure", "Akatsuki"],
      rank: "ANBU",
    },
    debut: { manga: "Chapter #139", anime: "Naruto Episode #80" },
    family: { father: "Fugaku Uchiha", mother: "Mikoto Uchiha", brother: "Sasuke Uchiha" },
    uniqueTraits: ["Mangekyō Sharingan", "Murdered his clan to protect Konoha", "Perfect Susanoo"],
  },
  {
    id: 11,
    name: "Jiraiya",
    images: ["https://static.wikia.nocookie.net/naruto/images/c/c0/J.png"],
    jutsu: ["Rasengan", "Sage Mode", "Summoning: Toad", "Fire Release: Toad Oil Flame Bullet"],
    natureType: ["Fire", "Earth", "Water", "Wind", "Lightning", "Yang"],
    personal: {
      birthdate: "November 11",
      sex: "Male",
      age: { "Part I": "50–51", "Part II": "54" },
      bloodType: "B",
      affiliation: ["Konohagakure", "Mount Myōboku"],
      rank: "Sannin",
    },
    debut: { manga: "Chapter #90", anime: "Naruto Episode #52" },
    uniqueTraits: ["Sage Mode", "One of the Legendary Sannin", "Naruto's godfather"],
  },
  {
    id: 12,
    name: "Tsunade",
    images: ["https://static.wikia.nocookie.net/naruto/images/0/0b/Tsunade_2.png"],
    jutsu: ["Byakugō no Jutsu", "Yin Seal Release", "Creation Rebirth", "Strength of a Hundred Seal"],
    natureType: ["Earth", "Water", "Fire", "Lightning", "Yang"],
    personal: {
      clan: "Senju Clan",
      birthdate: "August 2",
      sex: "Female",
      bloodType: "B",
      affiliation: ["Konohagakure"],
      rank: "Kage",
    },
    debut: { manga: "Chapter #148", anime: "Naruto Episode #83" },
    family: { grandfather: "Hashirama Senju", grandmother: "Mito Uzumaki" },
    uniqueTraits: ["Legendary Sannin", "5th Hokage", "Best medical ninja in the world"],
  },
  {
    id: 13,
    name: "Orochimaru",
    images: ["https://static.wikia.nocookie.net/naruto/images/2/2a/Orochimaru.png"],
    jutsu: ["Living Corpse Reincarnation", "Eight Branches Technique", "Edo Tensei", "Soft Physique Modification"],
    natureType: ["Fire", "Earth", "Wind", "Lightning", "Water"],
    personal: {
      birthdate: "October 27",
      sex: "Male",
      bloodType: "B",
      affiliation: ["Konohagakure", "Akatsuki", "Otogakure"],
      rank: "Sannin",
    },
    debut: { manga: "Chapter #45", anime: "Naruto Episode #27" },
    uniqueTraits: ["Can transfer between bodies", "Legendary Sannin", "Sought immortality"],
  },
  {
    id: 14,
    name: "Minato Namikaze",
    images: ["https://static.wikia.nocookie.net/naruto/images/a/a0/Minato.png"],
    jutsu: ["Flying Thunder God Technique", "Rasengan", "Shadow Clone Technique", "Sage Mode"],
    natureType: ["Wind", "Lightning", "Fire", "Earth", "Water"],
    personal: {
      birthdate: "January 25",
      sex: "Male",
      bloodType: "B",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      rank: "Kage",
    },
    debut: { manga: "Chapter #239", anime: "Naruto Episode #1" },
    family: { wife: "Kushina Uzumaki", son: "Naruto Uzumaki" },
    uniqueTraits: ["4th Hokage", "Yellow Flash of the Leaf", "Fastest ninja of his time"],
  },
  {
    id: 15,
    name: "Madara Uchiha",
    images: ["https://static.wikia.nocookie.net/naruto/images/9/9c/Madara.png"],
    jutsu: ["Susanoo", "Wood Release", "Rinnegan", "Infinite Tsukuyomi", "Limbo: Border Jail"],
    natureType: ["Fire", "Wind", "Lightning", "Earth", "Water", "Yin", "Yang"],
    personal: {
      clan: "Uchiha Clan",
      birthdate: "December 24",
      sex: "Male",
      bloodType: "O",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
    },
    debut: { manga: "Chapter #399", anime: "Naruto Shippūden Episode #322" },
    family: { brother: "Izuna Uchiha" },
    uniqueTraits: ["Co-founder of Konoha", "Eternal Mangekyō Sharingan", "Rinnegan", "Six Paths Sage Mode"],
  },
  {
    id: 16,
    name: "Obito Uchiha",
    images: ["https://static.wikia.nocookie.net/naruto/images/5/56/Tobi.png"],
    jutsu: ["Kamui", "Susanoo", "Wood Release", "Space–Time Migration"],
    natureType: ["Fire", "Water", "Earth", "Wind", "Lightning", "Yin", "Yang"],
    personal: {
      clan: "Uchiha Clan",
      birthdate: "February 10",
      sex: "Male",
      bloodType: "O",
      affiliation: ["Konohagakure", "Akatsuki"],
    },
    debut: { manga: "Chapter #239", anime: "Naruto Episode #49" },
    family: { grandmother: "Nohara family" },
    uniqueTraits: ["Mangekyō Sharingan", "Half-body made of Hashirama cells", "Jinchūriki of the Ten-Tails"],
  },
  {
    id: 17,
    name: "Pain (Nagato)",
    images: ["https://static.wikia.nocookie.net/naruto/images/8/87/Nagato.png"],
    jutsu: ["Shinra Tensei", "Chibaku Tensei", "Animal Path", "Human Path", "Planetary Devastation"],
    natureType: ["Wind", "Lightning", "Earth", "Water", "Fire", "Yin", "Yang"],
    personal: {
      clan: "Uzumaki Clan",
      birthdate: "September 19",
      sex: "Male",
      bloodType: "A",
      affiliation: ["Amegakure", "Akatsuki"],
    },
    debut: { manga: "Chapter #238", anime: "Naruto Shippūden Episode #128" },
    uniqueTraits: ["Rinnegan", "Six Paths of Pain", "Lead Akatsuki"],
  },
  {
    id: 18,
    name: "Konan",
    images: ["https://static.wikia.nocookie.net/naruto/images/4/41/Konan.png"],
    jutsu: ["Paper Ninjutsu", "Dance of the Shikigami", "Paper Person of God Technique"],
    natureType: ["Water", "Wind", "Fire"],
    personal: {
      birthdate: "February 20",
      sex: "Female",
      bloodType: "O",
      affiliation: ["Amegakure", "Akatsuki"],
    },
    debut: { manga: "Chapter #238", anime: "Naruto Shippūden Episode #128" },
    uniqueTraits: ["Can transform her body into paper", "Co-founded Akatsuki", "Angel of Amegakure"],
  },
  {
    id: 19,
    name: "Killer B",
    images: ["https://static.wikia.nocookie.net/naruto/images/6/64/Killer_B.png"],
    jutsu: ["Supervibrato Lightning Release Swords", "Lariat", "Lightning Release: Lariat", "Version 2"],
    natureType: ["Lightning"],
    personal: {
      birthdate: "June 12",
      sex: "Male",
      bloodType: "B",
      affiliation: ["Kumogakure", "Allied Shinobi Forces"],
      rank: "Jonin",
    },
    debut: { manga: "Chapter #412", anime: "Naruto Shippūden Episode #143" },
    family: { brother: "A (Fourth Raikage)" },
    uniqueTraits: ["Jinchūriki of Gyūki (Eight-Tails)", "Perfect Jinchūriki control", "Loves rap"],
  },
  {
    id: 20,
    name: "Might Guy",
    images: ["https://static.wikia.nocookie.net/naruto/images/5/51/Guy.png"],
    jutsu: ["Eight Gates", "Evening Elephant", "Night Guy", "Dynamic Entry", "Primary Lotus"],
    natureType: [],
    personal: {
      birthdate: "January 1",
      sex: "Male",
      bloodType: "B",
      affiliation: ["Konohagakure", "Allied Shinobi Forces"],
      rank: "Jonin",
    },
    debut: { manga: "Chapter #36", anime: "Naruto Episode #21" },
    family: { father: "Duy" },
    uniqueTraits: ["Eight Gates master", "Strongest Taijutsu user", "Forced Madara to use his 'real power'"],
  },
];

export const searchMock = (name) => {
  const q = name.toLowerCase();
  return mockCharacters.filter((c) => c.name.toLowerCase().includes(q));
};
